# Generated by Django 3.2.7 on 2021-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
