# Generated by Django 3.2.7 on 2021-09-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomrecordmanager',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
