# Generated by Django 3.2.7 on 2021-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_chatroomrecordmanager_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomrecordmanager',
            name='active_members',
            field=models.IntegerField(default=0),
        ),
    ]
