# Generated by Django 3.2.7 on 2021-09-28 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0003_chatroomrecordmanager_active_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatRoomRecordManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroomcode', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('active_members', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(verbose_name=True)),
                ('password', models.TextField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
